galasa-dev/maven

README.md
add overview and links to more info
=> update maven read me

galasa-maven-plugin/pom.xml
=> Move to 0.7.0

galasa-maven-plugin/pom.xml
=> Move to 0.8.0-SNAPSHOT

galasa-maven-plugin/pom.xml
=> Move to 0.8.0

galasa-maven-plugin/pom.xml
=> Move to 0.9.0-SNAPSHOT

galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildBundleTestCatalog.java
=> Correct reporting of testcatalog counts

galasa-maven-plugin/pom.xml
=> rearrange elements for version updates

galasa-maven-plugin/pom.xml
=> Version 0.9.0

galasa-maven-plugin/pom.xml
=> version 0.10.0-SNAPSHOT

galasa-maven-plugin/pom.xml
=> Version 0.10.0

galasa-maven-plugin/pom.xml
=> Version 0.11.0-SNAPSHOT

galasa-maven-plugin/pom.xml
=> Version 0.11.0

galasa-maven-plugin/pom.xml
=> Version 0.12.0-SNAPSHOT

README.md
Signed-off-by: Diana Slepikaite <d.slepikaite@gmail.com>
=> eddited readme spectrum to slack

galasa-maven-plugin/pom.xml
=> Version 0.12.0

galasa-maven-plugin/pom.xml
=> Version 0.13.0-SNAPSHOT

galasa-maven-plugin/pom.xml
=> Version 0.13.0

galasa-maven-plugin/pom.xml
=> Version 0.14.0-SNAPSHOT

galasa-maven-plugin/pom.xml
=> Version 0.14.0

galasa-maven-plugin/pom.xml
=> Version 0.15.0-SNAPSHOT

galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildOBRResources.java
=> Strip the EE dependency from the OBR

galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/MergeTestCatalogs.java
=> Allow maven obr build to support new testcatalog format

galasa-maven-plugin/pom.xml
=> gpg key expired

galasa-maven-plugin/pom.xml
=> Version 0.15.0

docker/Dockerfile, galasa-maven-plugin/pom.xml, tekton/pipe-maven-repo-build.yaml, tekton/prun-main-maven-build.yaml, tekton/res-git-maven-main.yaml, tekton/res-git-maven-staging.yaml, tekton/task-maven-repo-build.yaml
=> add tekton and bump commons.io

tekton/prun-main-maven-build.yaml, tekton/task-maven-repo-build.yaml
=> new k8s standards

README.md, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/MergeTestCatalogs.java
Signed-off-by: James Davies <jdavies47@hotmail.co.uk>
=> Changed readme links and comments for words matter

tekton/pipe-maven-repo-build.yaml, tekton/prun-main-maven-build.yaml, tekton/task-maven-repo-build.yaml
=> Tekton changes

tekton/task-maven-repo-build.yaml
=> tekton updates

galasa-maven-plugin/pom.xml, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/MergeTestCatalogs.java
=> allow merging of adhoc categories

README.md, build-locally.sh
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>
Make it easy to build this repo using the command-line, locally.
=> Able to build locally with a script

.gitignore, galasa-maven-plugin/pom.xml, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildOBRResources.java
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>
=> more logging

build-locally.sh, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildBundleTestCatalog.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildGherkinTestCatalog.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildGherkinZip.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildMavenRepository.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildOBRResources.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/BuildObrEmbeddedRepository.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/DeployTestCatalog.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/MergeTestCatalogs.java, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/StoreGitCommitHash.java
./Contributions.md contained "Copyright (C) 2004, 2006 The Linux Foundation and its contributors." which is fine, so was left untouched
=> copyright changes applied

galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/DeployTestCatalog.java
Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>
Story: https://github.com/galasa-dev/projectmanagement/issues/1755
=> javadoc explaining the use of setCorrectBooleanValue

galasa-maven-plugin/pom.xml, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/DeployTestCatalog.java
Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>
=> added loggings to find root of inttests error

galasa-maven-plugin/pom.xml, galasa-maven-plugin/src/main/java/dev/galasa/maven/plugin/DeployTestCatalog.java
Removed redundant logging dependencies 
Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>
=> improving loggings

.github/workflows/build.yaml
Contributes to issue https://github.com/galasa-dev/projectmanagement/issues/1958 - parameterising the build workflow to support any branch/tag.
=> Parameterise main build workflow to support any branch/tag

.github/workflows/build.yaml
For https://github.com/galasa-dev/projectmanagement/issues/1996
=> Iss1996 - add report failed build job
